force-app/main/default/objects/First__c/First__c.object-meta.xml
<CustomObject>
    <label>First</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Firsts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/First__c/fields/Second__c.field-meta.xml
<CustomField>
    <fullName>Second__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Second</label>
    <referenceTo>Second__c</referenceTo>
    <relationshipLabel>Firsts</relationshipLabel>
    <relationshipName>Firsts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Second__c/Second__c.object-meta.xml
<CustomObject>
    <label>Second</label>
    <nameField>
        <label>Second Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seconds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Second__c/fields/Third__c.field-meta.xml
<CustomField>
    <fullName>Third__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Third</label>
    <referenceTo>Third__c</referenceTo>
    <relationshipLabel>Seconds</relationshipLabel>
    <relationshipName>Seconds</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Third__c/Third__c.object-meta.xml
<CustomObject>
    <label>Third</label>
    <nameField>
        <label>Third Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Thirds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TableTestController.cls
public with sharing class TableTestController {

    @AuraEnabled(cacheable=true)
    public static List<TableTestWrapper> getListOfFirsts(Integer maximum, Integer offset) {
        List<First__c> listOfFirsts =  FirstDAO.fetchAll(maximum, offset);
        List<TableTestWrapper> wrappers = new List<TableTestWrapper>();
        for (First__c first : listOfFirsts) {
            wrappers.add(new TableTestWrapper(first.Name, first.Second__r.Name, first.Second__r.Third__r.Name));
        }

        return wrappers;
    }

    public class TableTestWrapper {
        @AuraEnabled
        public String firstName { get; set; }
        @AuraEnabled
        public String secondName { get; set; }
        @AuraEnabled
        public String thirdName { get; set; }
    
        public TableTestWrapper(String firstName, String secondName, String thirdName) {
            this.firstName = firstName;
            this.secondName = secondName;
            this.thirdName = thirdName;
        }
    }
}